spring:
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: admin
      database: customers-test
      port: 27017
      host: localhost
      auto-index-creation: true
